### ISSUE TITLE
Trying to run the config

### ISSUE THREAD

**Issue by sohanglal** [Feel-ix-343/Neovim-Config#1]
I am trying to get your neovim config to run. However I am running into some issues:

Following are the list of commands that I am running and their corresponding errors. 

`rm -v -rf ~/.local/share/nvim`
`git clone https://github.com/Feel-ix-343/Neovim-Config.git`
`cd Neovim-Config/`
`nvim -u ./init.lua`

Error:

```
Error detected while processing /home/sl/test/Neovim-Config/init.lua:
E5113: Error while calling lua chunk: /home/sl/test/Neovim-Config/init.lua:22: module 'envs' not found:
        no field package.preload['envs']
```
After commenting out line 22 this is the error I get 
```
Error detected while processing /home/sl/test/Neovim-Config/init.lua:
No specs found for module plugin
E5113: Error while calling lua chunk: /home/sl/test/Neovim-Config/init.lua:32: module 'generalkeymaps' not
 found:
        no field package.preload['generalkeymaps']
```

**Comment by Feel-ix-343** [comment]
Yea I don't update this frequently :smile: sorry! I will start though, seeing as people may view it as an example for [moxide](https://github.com/Feel-ix-343/markdown-oxide). 

- For the `envs` error; This happens because I don't upload my envs (openai-api key) to the repo. You will need to create an envs file for this yourself. You can also see in the .gitignore that envs.lua is ignored. Commenting out the line should also work I think. 
- Require "generalkeymaps" should work given that a file `lua/generalkeymaps.lua` exists. Make sure that you have this plugin updated and that that file exists. 

Let me know if this still doesn't work.

**Comment by sohanglal** [comment]
It is working well now. Maybe the issue was that I was trying to run `nvim -u ./init.lua`. 
Once I symlinked your config in $XDG_HOME it worked fine. 
Thanks

**Comment by Feel-ix-343** [comment]
Oh it may be lazyvim related. 

Im not familiar with -u though
